"use client";

import {
  Wifi,
  Plug,
  Lock,
  Tv,
  Smartphone,
  Monitor,
  Shirt,
  Droplets,
  Wind,
  RefreshCw,
  Sun,
  Sparkles,
  Coffee,
  Flame,
  UtensilsCrossed,
  Refrigerator,
  ChefHat,
  Briefcase,
  FileText,
  HeartPulse,
  Shield,
  Bell,
  CircleAlert,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { AmenityKey } from "./amenities";

export const AMENITY_ICONS: Record<AmenityKey, LucideIcon> = {
  wifi_fast: Wifi,
  universal_adapter: Plug,
  smart_lock: Lock,
  ott: Tv,
  pocket_wifi: Smartphone,
  workspace: Monitor,
  bath_towel: Shirt,
  bidet: Droplets,
  hair_dryer: Wind,
  washing_machine: RefreshCw,
  clothes_dryer: Sun,
  iron: Sparkles,
  water_purifier: Droplets,
  coffee_machine: Coffee,
  microwave: Flame,
  electric_kettle: UtensilsCrossed,
  refrigerator: Refrigerator,
  cooking_basics: ChefHat,
  luggage_storage: Briefcase,
  trash_guide_en: FileText,
  first_aid_kit: HeartPulse,
  fire_extinguisher: Shield,
  smoke_alarm: Bell,
  carbon_monoxide_detector: CircleAlert,
};
